# Included from ../../Makefile; paths are relative to src/.

LINUX_LOADER_OBJS := linux_loader.o
LINUX_LOADER_C_OBJS := $(LINUX_LOADER_OBJS)

linux_loader.o: app/linux_loader/linux_loader.c
	$(COMPILE_C)
