# Included from ../../Makefile; paths are relative to src/.

bios_memory.o: lib/x86/bios_memory.c
	$(COMPILE_C)

bios_nvram.o: lib/x86/bios_nvram.c
	$(COMPILE_C)

bios_rtc.o: lib/x86/bios_rtc.c
	$(COMPILE_C)
