#ifndef BIOS_NVRAM_H
#define BIOS_NVRAM_H

#define BIOS_NVRAM_MAGIC 0x334e5842u
#define BIOS_NVRAM_SIZE 128u
#define BIOS_NVRAM_PARTITION_OFF 4u
#define BIOS_NVRAM_FLAGS0_OFF 5u
#define BIOS_NVRAM_BOOT_PRIORITY_OFF 6u
#define BIOS_NVRAM_CMDLINE_OFF 7u
#define BIOS_NVRAM_CMDLINE_MAX (BIOS_NVRAM_SIZE - BIOS_NVRAM_CMDLINE_OFF)

#define BIOS_NVRAM_FLAGS0_MEMTEST 0x01u
#define BIOS_NVRAM_FLAGS0_SERIAL_CONSOLE 0x02u
#define BIOS_NVRAM_FLAGS0_VESA_1024_768 0x04u
#define BIOS_NVRAM_FLAGS0_RUN_TEST_BLOB 0x08u
#define BIOS_NVRAM_FLAGS0_KNOWN_MASK 0x0fu
#define BIOS_NVRAM_FLAGS0_DEFAULT BIOS_NVRAM_FLAGS0_SERIAL_CONSOLE

#define BIOS_NVRAM_BOOT_PRIORITY_AUTO 0u
#define BIOS_NVRAM_BOOT_PRIORITY_IDE 1u
#define BIOS_NVRAM_BOOT_PRIORITY_USB 2u
#define BIOS_NVRAM_BOOT_PRIORITY_DEFAULT BIOS_NVRAM_BOOT_PRIORITY_AUTO

#endif
