#pragma once

#include <uacpi/helpers.h>
#include <uacpi/log.h>

#define UACPI_DEFAULT_LOG_LEVEL UACPI_LOG_WARN
#define UACPI_DEFAULT_LOOP_TIMEOUT_SECONDS 2
#define UACPI_DEFAULT_MAX_CALL_STACK_DEPTH 32
#define UACPI_STATIC_TABLE_ARRAY_LEN 8
#define UACPI_PLAIN_LOG_BUFFER_SIZE 96

#define UACPI_PHYS_ADDR_IS_32BITS
#define UACPI_USE_BUILTIN_STRING
